{% set name = "libmbd" %}
{% set version = "0.12.3" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libmbd/libmbd/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba234f34956f803c2e9eac1ddf0d423c6f232288bfdf10fb0bd932864b1471fa
  patches:
    - mpi-option.patch
    - gradient-threshold.patch

{% if mpi == "nompi" %}
{% set build = build + 100 %}
{% endif %}
build:
  number: {{ build }}
  skip: true  # [win]

  {% if mpi != "nompi" %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  {% if mpi != "nompi" %}
  run_exports:
    - {{ name }} * {{ mpi_prefix }}_*
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    - elsi  # [mpi != "nompi"]
    - libblas
    - liblapack
  run:
    - {{ mpi }}  # [mpi != "nompi"]
    - scalapack  # [mpi != "nompi"]
    - elsi  # [mpi != "nompi"]

test:
  commands:
    - test -f $PREFIX/lib/libmbd${SHLIB_EXT}

about:
  home: https://github.com/libmbd/{{ name }}
  license: MPL-2.0
  license_file:
    - LICENSE
  summary: Many-body dispersion library
  doc_url: https://libmbd.github.io

extra:
  recipe-maintainers:
    - awvwgk
    - jhrmnn
